# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: crackcomputers.com
email: sandip.daw.cse@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 We the computer geeks welcome you to the most crazy site in web.
 Lets make some history.Lets Crack Computers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
facebook_username: sandip daw
github_username:  cracker-id00

# Build settings
markdown: kramdown
